name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Display Runner Details
      run: echo "The runner name is ${{ runner.name }} and the architecture is ${{ runner.arch }}"
