name: Calculate Average and Output

on:
  push:
    branches:
      - master

jobs:
  calculate_average:
    runs-on: ubuntu-latest
    outputs:
      average: ${{steps.set_reading_score.outputs.reading }}+ {{steps.set_writing_score.outputs.writing}} / 2
    steps:
    - id: set_reading_score
      run: echo "reading=80" >> $GITHUB_ENV
    - id: set_writing_score
      run: echo "writing=90" >> $GITHUB_ENV