name: Contexts Example

on:
  push:


jobs:
  job1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    outputs:
      example_output: "Hello, world!"
    steps:
    - name: Show runner OS
      run: echo "The runner operating system is ${{ runner.os }}"
  
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Use needs context
      run: echo "Output from job1 is ${{ needs.job1.outputs.example_output }}"
      
    - name: Use strategy context
      run: |
        echo "The index of the current job in the matrix is ${{ strategy.job-index }}"
        echo "The total number of jobs in the matrix is ${{ strategy.job-total }}"
